cinemaproject/cinemaproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('movies.urls')),
    path('users/', include('users.urls')),
  	path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinemaproject/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

cinemaproject/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
	path('movie/<slug:movie_slug>', views.movie, name='movie'),
	path('', views.catalog, name="catalog"),
    path('<int:page>', views.catalog, name='catalog'),
  
]

cinemaproject/users/urls.py
from django.urls import path, include
from .views import Register
from users import views


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
	path('profile', views.profile_page, name='profile'),
    path('register/', Register.as_view(), name='register'),
]

cinemaproject/main/models.py
from django.db import models

# Create your models here.

cinemaproject/movies/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=50, verbose_name='Жанр', blank=True, null=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    
    class Meta:
        db_table = 'Жанры'
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ("id",)

    def __str__(self):
        return self.name


class Movie(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название', blank=False)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(max_length=500, verbose_name='Описание', blank=False)
    created_year = models.DateField(null=True, blank=True)
    rating = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name='Рейтинг')
    avatar = models.ImageField(upload_to='movies_images', blank=True, null=True, verbose_name='Аватар')
    box_office = models.BigIntegerField(null=True, blank=True, verbose_name='Кассовые сборы')
    budgets = models.BigIntegerField(null=True, blank=True, verbose_name='Бюджет')
    video_file = models.FileField(upload_to='movie_videos', blank=True, null=True, verbose_name='Видео')
    genre = models.ForeignKey(to=Genre, on_delete=models.CASCADE, verbose_name='Жанр', null=True)
    

    class Meta:
        db_table = 'Фильмы'
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'
        ordering = ('id',) 
    
    def __str__(self):
        return self.name


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    is_positive = models.BooleanField(verbose_name='положительный', default=True)

    def __str__(self):
        return self.movie.name  + " " + self.user.username
    
    
    

cinemaproject/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    pass

cinemaproject/movies/forms.py
# forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'is_positive']
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Ваш комментарий', 'rows': 4, 'cols': 40}),
            'is_positive': forms.Select(choices=[(True, 'Положительный'), (False, 'Отрицательный')]),
        }
        label = {
            'content': 'Комментарий',
            'is_positive': 'Положительный',
        }

cinemaproject/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class UserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = ''
        self.fields['password1'].help_text = ''  # Убираем стандартный help_text для поля password1
        self.fields['password2'].help_text = ''
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username',  'password1', 'password2',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'Введите ваше имя'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Введите вашу фамилию'}),
            'username': forms.TextInput(attrs={'placeholder': 'Введите ваше имя пользователя'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Введите ваш email'}),
        }

cinemaproject/main/views.py
from django.shortcuts import render


def index(request):
	return render(request, 'main/index.html')

def about(request):
	return render(request, 'main/about.html')

cinemaproject/movies/views.py
from django.http import Http404
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.template import context
from .models import Movie, Genre, Comment
from .forms import CommentForm
# Create your views here.

def catalog(request, page=1):
    query = request.GET.get('q', None)
    rating = request.GET.get('rating', None)
    selected_genres = request.GET.getlist('genres', None)
    
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    

    if query:
        movies = movies.filter(name__icontains=query)
    if rating:
        movies = movies.filter(rating__gte=rating)
    if selected_genres:
        movies = movies.filter(genre__id__in=selected_genres).distinct()
        
    # if not movies.exists():
    #     raise Http404("No movies found matching the criteria.")
    
    paginator = Paginator(movies, 4)
    current_page = paginator.page(page)
        
    context = {
        'movies': current_page,
        'genres': genres
  }
    return render(request, 'movies/catalog.html', context)


def movie(request, movie_slug):
    movie = Movie.objects.get(slug=movie_slug)
    comments = Comment.objects.filter(movie=movie).order_by('-created_at')

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
            #return redirect(f'{movie_slug}')
    else:
        form = CommentForm()

    context = {
        'movie': movie,
        'comments': comments,
        'form': form,
  }
    return render(request, 'movies/movie.html', context)

cinemaproject/users/views.py
from re import L
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.decorators import login_required

from users.forms import UserCreationForm, UserProfileForm


# Create your views here.
class Register(View):

    template_name = 'registration/register.html'

    def get(self, request):
        context = {
            'form': UserCreationForm()
        }

        return render(request, self.template_name, context)

    def post(self, request):

        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')

            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')

        context ={
            'form': form
        }
        return render(request, self.template_name, context)
    
@login_required
def profile_page(request):
	user = request.user
    
	if request.method == 'POST':
		form = UserProfileForm(request.POST, instance=user)
		if form.is_valid():
			form.save()
			return redirect('profile')
	else:
		form = UserProfileForm(instance=user)
                  
	return render(request, 'users/profile.html', {'form': form})

cinemaproject/main/templates/main/about.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}
<h2>About Us</h2>
<p>Welcome to Kinopoisk. It will be a pet-project on Django. We want to include such things as:</p>
<ul>
	<li>1. Creating templates and load static files</li>
	<li>2. Work with Postrgresql</li>
	<li>3. Pagination</li>
	<li>4. Authentification and registration</li>
	<li>5. Fulltext search</li>
	<li>Coming soon...</li>
</ul>
{% endblock %}

cinemaproject/main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<section class="container">
    <h2>Прямо сейчас в кинотеатрах</h2>
    <div class="movie-list">
        <!-- Example movie item -->
        <div class="movie">
            <img src="{% static 'deps/images/movie-poster.jpg' %}" alt="Movie Title">
            <h3>Оппенгеймер</h3>
            <p class="text-truncate">"Оппенгеймер" — это предстоящий фильм режиссёра Кристофера Нолана, посвящённый жизни и деятельности Роберта Оппенгеймера, 
                известного физика и ключевой фигуры в разработке атомной бомбы во время Второй мировой войны. 
                Фильм планируется как биографическая драма, освещающая сложные этические и научные аспекты проекта Манхэттен.</p>
            <a href="#" class="btn">Подробнее</a>
        </div>
        <!-- Add more movie items if needed -->
    </div>
</section>
{% endblock %}

cinemaproject/movies/templates/movies/catalog.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block title %}Catalog{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static "deps/css/catalog.css" %}">
<section class="container">
    <h2>Catalog</h2>

    <button class="btn btn-primary btn-primary-custom" onclick="toggleMenu()">Filters</button>
    <div id="overlay" class="overlay" onclick="closeMenu()"></div>
    <div id="sidebar" class="sidebar">
        <form action="{% url 'movies:catalog' %}" method="get">
            <div class="form-group">
                <label for="rating">Rating</label>
                <div class="rating-filter">
                    <input type="hidden" id="rating" name="rating" value="0">
                    <span class="star" data-value="1">★</span>
                    <span class="star" data-value="2">★</span>
                    <span class="star" data-value="3">★</span>
                    <span class="star" data-value="4">★</span>
                    <span class="star" data-value="5">★</span>
                    <span class="star" data-value="6">★</span>
                    <span class="star" data-value="7">★</span>
                    <span class="star" data-value="8">★</span>
                    <span class="star" data-value="9">★</span>
                    <span class="star" data-value="10">★</span>
                </div>
            </div>
            <div class="form-group">
                <label for="genres">Genres</label>
                <select id="genres" name="genres" class="form-control" multiple>
                    {% for genre in genres %}
                        <option value="{{ genre.id }}">{{ genre.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Apply Filters</button>
        </form>
    </div>

    <div class="movie-list">
        {% for movie in movies %}
        <div class="movie-card">
            <img src="{{ movie.avatar.url }}" alt="{{ movie.name }}" class="movie-poster">
            <div class="movie-info">
                <h3>{{ movie.name }}</h3>
                <p>{{ movie.description|truncate_chars:100 }}</p>
                <p>Рейтинг: {{ movie.rating }}</p>
                <p>ID: {{ movie.id }}</p>
                <a href="{% url "movies:movie" movie.slug %}" class="btn">View Details</a>
            </div>
        </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center my-4">
            <div class="custom-shadow d-flex">
                <li class="page-item {% if not movies.has_previous %}disabled{% endif %}">
                    <a class="page-link" href="{% if movies.has_previous %}{% url "movies:catalog" movies.previous_page_number %}{% else %}#{% endif %}">Previous</a>
                </li>
                {% for page in movies.paginator.page_range %}
                    {% if page >= movies.number|add:-2 and page <= movies.number|add:2 %}
                        <li class="page-item {% if movies.number == page %}active{% endif %}">
                            <a class="page-link" href="{% url "movies:catalog" page %}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                <li class="page-item {% if not movies.has_next %}disabled{% endif %}">
                    <a class="page-link" href="{% if movies.has_next %}{% url "movies:catalog" movies.next_page_number %}{% else %}#{% endif %}">Next</a>
                </li>
            </div>
        </ul>
    </nav>
</section>

<script>
function toggleMenu() {
    var sidebar = document.getElementById('sidebar');
    var overlay = document.getElementById('overlay');
    sidebar.classList.toggle('active');
    overlay.classList.toggle('active');
}

function closeMenu() {
    var sidebar = document.getElementById('sidebar');
    var overlay = document.getElementById('overlay');
    sidebar.classList.remove('active');
    overlay.classList.remove('active');
}

document.addEventListener('click', function(event) {
    var sidebar = document.getElementById('sidebar');
    var overlay = document.getElementById('overlay');
    var isClickInside = sidebar.contains(event.target) || event.target.matches('.btn-primary-custom');

    if (!isClickInside && sidebar.classList.contains('active')) {
        closeMenu();
    }
});
</script>
{% endblock %}

cinemaproject/movies/templates/movies/movie.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ movie.name }}{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'deps/css/movie.css' %}">
<section class="container">
    <div class="movie-detail">
        <img src="{{ movie.avatar.url }}" alt="{{ movie.name }}" class="movie-poster">
        <div class="movie-info">
            <h2>{{ movie.name }}</h2>
            <p>{{ movie.description }}</p>
            <p>Рейтинг: {{ movie.rating }}</p>
            <p>Жанр: {{ movie.genre }}</p>
            <p>Дата релиза: {{ movie.created_year }}</p>
            <p>Бюджет: {{ movie.box_office }}.000.000 $</p>
        </div>

        {% if movie.video_file %}
        <div class="movie-video">
            <h3>Смотреть трейлер</h3>
            <video controls width="600">
                <source src="{{ movie.video_file.url }}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        </div>
    	{% endif %}

    
        <div class="comments-section">
            <h2>Комментарии</h2>
            {% if user.is_authenticated %}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Отправить</button>
                </form>
            {% else %}
                <p>Пожалуйста, <a href="{% url 'login' %}">войдите</a>, чтобы оставить комментарий.</p>
            {% endif %}
            <div id="comments-container">
                <br>
                {% for comment in comments %}
                    {% if comment.is_positive %}
                    <div class="comment-positive">
                        <p><strong>{{ comment.user.username }}</strong> ({{ comment.created_at|date:"d M Y" }}):</p>
                        <p>{{ comment.text }}</p>
                    </div>
                    {% else %}
                    <div class="comment-negative">
                        <p><strong>{{ comment.user.username }}</strong> ({{ comment.created_at| date:"d M Y" }}):</p>
                        <p>{{ comment.text }}</p>
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>


</section>
{% endblock %}

cinemaproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <title>Kinopoisk-like Site</title>
    <link rel="stylesheet" href="{% static 'deps/css/styles.css' %}">
</head>
<body>
    <header>
        <div class="container header-content">
            <h2>Kinopoisk</h2>
            <nav>
                <ul class="nav-menu">
                    <li><a href="{% url "main:index" %}">Home</a></li>
                    <li><a href="{% url "movies:catalog" %}">Movies</a></li>
                    <li><a href="{% url "main:about" %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="nav-link logout-button">Log out</button>
                            </form>
                        </li>
						<li><a href="{% url 'profile' %}">Profile</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <form class="d-flex search-form" role="search" action="{% url 'movies:catalog' %}" method="get">
                    <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success text-white" type="submit">Search</button>
                </form>
            </nav>
        </div>
    </header>

    <main class="container">
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </main>

	
    <script src="{% static 'deps/js/stars.js' %}"></script>
</body>
</html>

cinemaproject/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}



{% block title %}Профиль{% endblock %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-5">
                <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}